CREATE TABLE [dbo].[FrontUser] (
    [Id]          BIGINT    IDENTITY(1,1) NOT NULL,
    [Name]         NVARCHAR(300)  NULL,
    [FirstName]    NVARCHAR(150)  NULL,
    [LastName]     NVARCHAR(150)  NULL,
    [Email]        NVARCHAR(300)  NULL,
    [MobileNumber] NVARCHAR(20)   NULL,
    [DateOfBirth]  DATETIME2      NULL,
    [ProfileImg]   NVARCHAR(500)  NULL,
    [StateId]      INT            NULL,
    [AuthToken]    NVARCHAR(MAX)  NULL,
    [Provider]     NVARCHAR(100)  NULL,
    [FCMToken]     NVARCHAR(500)  NULL,
    [Platform]     NVARCHAR(50)   NULL,
    [UId]          NVARCHAR(200)  NULL,
    [Language]     NVARCHAR(10)   NULL DEFAULT 'en',
    -- Audit
    [IsActive]    BIT              NOT NULL DEFAULT 1,
    [IsDelete]    BIT              NOT NULL DEFAULT 0,
    [CreatedDate] DATETIME2        NOT NULL DEFAULT GETUTCDATE(),
    [ModifiedDate] DATETIME2       NULL,
    [CreatedBy]   INT              NOT NULL DEFAULT 0,
    [ModifiedBy]  INT              NULL,
    [IPAddress]   NVARCHAR(50)     NULL,
    [IPCity]      NVARCHAR(100)    NULL,
    [IPCountry]   NVARCHAR(100)    NULL,
    [Browser]     NVARCHAR(200)    NULL,
    [ScreenName]  NVARCHAR(200)    NULL,
    CONSTRAINT [PK_FrontUser] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO
