CREATE TABLE [dbo].[BlockContents] (
    [Id]                       INT              IDENTITY(1,1) NOT NULL,
    [Title]                    NVARCHAR(500)    NOT NULL,
    [TitleHindi]               NVARCHAR(500)    NULL,
    [BlockTypeId]              INT              NOT NULL,
    [RecruitmentId]            INT              NULL,
    [DepartmentId]             INT              NULL,
    [CategoryId]               INT              NULL,
    [SubCategoryId]            INT              NULL,
    [GroupId]                  INT              NULL,
    [StateId]                  INT              NULL,
    [UrlLabelId]               INT              NULL,
    [ExamMode]                 INT              NULL,
    [Url]                      NVARCHAR(500)    NULL,
    [SlugUrl]                  NVARCHAR(500)    NOT NULL,
    [NotificationLink]         NVARCHAR(500)    NULL,
    [OtherLinks]               NVARCHAR(MAX)    NULL,
    [SortLinks]                NVARCHAR(MAX)    NULL,
    [Description]              NVARCHAR(MAX)    NULL,
    [DescriptionHindi]         NVARCHAR(MAX)    NULL,
    [DescriptionJson]          NVARCHAR(MAX)    NULL,
    [DescriptionHindiJson]     NVARCHAR(MAX)    NULL,
    [Summary]                  NVARCHAR(MAX)    NULL,
    [SummaryHindi]             NVARCHAR(MAX)    NULL,
    [HowTo]                    NVARCHAR(MAX)    NULL,
    [Keywords]                 NVARCHAR(1000)   NULL,
    [KeywordsHindi]            NVARCHAR(1000)   NULL,
    [Thumbnail]                NVARCHAR(500)    NULL,
    [ThumbnailCredit]          NVARCHAR(300)    NULL,
    [SocialMediaUrl]           NVARCHAR(500)    NULL,
    [Date]                     DATETIME2        NULL,
    [LastDate]                 DATETIME2        NULL,
    [ExtendedDate]             DATETIME2        NULL,
    [FeePaymentLastDate]       DATETIME2        NULL,
    [CorrectionLastDate]       DATETIME2        NULL,
    [PublishedDate]            DATETIME2        NULL,
    [ShouldReminder]           DATETIME2        NULL,
    [ReminderDescription]      NVARCHAR(500)    NULL,
    [UpcomingCalendarCode]     INT              NULL,
    [Status]                   INT              NULL,
    [VisitCount]               INT              NULL DEFAULT 0,
    [PublisherId]              INT              NULL,
    [IsCompleted]              BIT              NULL DEFAULT 0,
    [IsExpired]                BIT              NULL DEFAULT 0,
    -- Audit
    [IsActive]                 BIT              NOT NULL DEFAULT 1,
    [IsDelete]                 BIT              NOT NULL DEFAULT 0,
    [CreatedDate]              DATETIME2        NOT NULL DEFAULT GETUTCDATE(),
    [ModifiedDate]             DATETIME2        NULL,
    [CreatedBy]                INT              NOT NULL DEFAULT 0,
    [ModifiedBy]               INT              NULL,
    [IPAddress]                NVARCHAR(50)     NULL,
    [IPCity]                   NVARCHAR(100)    NULL,
    [IPCountry]                NVARCHAR(100)    NULL,
    [Browser]                  NVARCHAR(200)    NULL,
    [ScreenName]               NVARCHAR(200)    NULL,
    CONSTRAINT [PK_BlockContents] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO

CREATE NONCLUSTERED INDEX [IX_BlockContent_ActiveDelete]
    ON [dbo].[BlockContents] ([IsActive] ASC, [IsDelete] ASC)
    INCLUDE ([BlockTypeId], [CategoryId], [PublishedDate]);
GO
