CREATE TABLE [dbo].[Scheme] (
    [Id]                      INT              IDENTITY(1,1) NOT NULL,
    [Title]                   NVARCHAR(500)    NOT NULL,
    [TitleHindi]              NVARCHAR(500)    NULL,
    [DepartmentId]            INT              NULL,
    [StateId]                 INT              NULL,
    [BlockTypeCode]           INT              NULL,
    [LevelType]               INT              NULL,
    [Mode]                    INT              NULL,
    [MinAge]                  INT              NULL,
    [MaxAge]                  INT              NULL,
    [StartDate]               DATETIME2        NULL,
    [EndDate]                 DATETIME2        NULL,
    [ExtendedDate]            DATETIME2        NULL,
    [CorrectionLastDate]      DATETIME2        NOT NULL DEFAULT GETUTCDATE(),
    [PostponeDate]            DATETIME2        NULL,
    [ShouldReminder]          DATETIME2        NULL,
    [ReminderDescription]     NVARCHAR(500)    NULL,
    [UpcomingCalendarCode]    INT              NULL,
    [PublishedDate]           DATETIME2        NULL,
    [OfficelLink]             NVARCHAR(500)    NULL,
    [ApplyLink]               NVARCHAR(500)    NULL,
    [OtherLinks]              NVARCHAR(MAX)    NULL,
    [SortLinks]               NVARCHAR(MAX)    NULL,
    [ContactDetail]           NVARCHAR(MAX)    NULL,
    [Fee]                     NVARCHAR(200)    NULL,
    [ShortDescription]        NVARCHAR(1000)   NULL,
    [ShortDescriptionHindi]   NVARCHAR(1000)   NULL,
    [Description]             NVARCHAR(MAX)    NULL,
    [DescriptionHindi]        NVARCHAR(MAX)    NULL,
    [DescriptionJson]         NVARCHAR(MAX)    NULL,
    [DescriptionHindiJson]    NVARCHAR(MAX)    NULL,
    [HowtoApply]              NVARCHAR(MAX)    NULL,
    [Keywords]                NVARCHAR(1000)   NULL,
    [KeywordsHindi]           NVARCHAR(1000)   NULL,
    [Slug]                    NVARCHAR(500)    NOT NULL,
    [Thumbnail]               NVARCHAR(500)    NULL,
    [ThumbnailCredit]         NVARCHAR(300)    NULL,
    [SocialMediaUrl]          NVARCHAR(500)    NULL,
    [Status]                  INT              NULL,
    [VisitCount]              INT              NULL DEFAULT 0,
    [PublisherId]             INT              NULL,
    [IsCompleted]             BIT              NULL DEFAULT 0,
    [IsExpired]               BIT              NULL DEFAULT 0,
    -- Audit
    [IsActive]                BIT              NOT NULL DEFAULT 1,
    [IsDelete]                BIT              NOT NULL DEFAULT 0,
    [CreatedDate]             DATETIME2        NOT NULL DEFAULT GETUTCDATE(),
    [ModifiedDate]            DATETIME2        NULL,
    [CreatedBy]               INT              NOT NULL DEFAULT 0,
    [ModifiedBy]              INT              NULL,
    [IPAddress]               NVARCHAR(50)     NULL,
    [IPCity]                  NVARCHAR(100)    NULL,
    [IPCountry]               NVARCHAR(100)    NULL,
    [Browser]                 NVARCHAR(200)    NULL,
    [ScreenName]              NVARCHAR(200)    NULL,
    CONSTRAINT [PK_Scheme] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO

CREATE NONCLUSTERED INDEX [IX_Scheme_ActiveDelete]
    ON [dbo].[Scheme] ([IsActive] ASC, [IsDelete] ASC)
    INCLUDE ([BlockTypeCode], [DepartmentId], [PublishedDate]);
GO
