CREATE TABLE [dbo].[DepartmentMaster] (
    [Id]                    INT              IDENTITY(1,1) NOT NULL,
    [Name]                  NVARCHAR(300)    NULL,
    [NameHindi]             NVARCHAR(300)    NULL,
    [ShortName]             NVARCHAR(100)    NULL,
    [Address]               NVARCHAR(500)    NULL,
    [AddressHindi]          NVARCHAR(500)    NULL,
    [MapUrl]                NVARCHAR(500)    NULL,
    [Email]                 NVARCHAR(200)    NULL,
    [PhoneNumber]           NVARCHAR(50)     NULL,
    [Logo]                  NVARCHAR(500)    NULL,
    [Url]                   NVARCHAR(500)    NULL,
    [SlugUrl]               NVARCHAR(500)    NOT NULL,
    [Description]           NVARCHAR(MAX)    NULL,
    [DescriptionJson]       NVARCHAR(MAX)    NULL,
    [DescriptionHindi]      NVARCHAR(MAX)    NULL,
    [DescriptionHindiJson]  NVARCHAR(MAX)    NULL,
    [FaceBookLink]          NVARCHAR(500)    NULL,
    [TwitterLink]           NVARCHAR(500)    NULL,
    [WikipediaEnglishUrl]   NVARCHAR(500)    NULL,
    [WikipediaHindiUrl]     NVARCHAR(500)    NULL,
    [StateId]               INT              NULL,
    -- Audit
    [IsActive]              BIT              NOT NULL DEFAULT 1,
    [IsDelete]              BIT              NOT NULL DEFAULT 0,
    [CreatedDate]           DATETIME2        NOT NULL DEFAULT GETUTCDATE(),
    [ModifiedDate]          DATETIME2        NULL,
    [CreatedBy]             INT              NOT NULL DEFAULT 0,
    [ModifiedBy]            INT              NULL,
    [IPAddress]             NVARCHAR(50)     NULL,
    [IPCity]                NVARCHAR(100)    NULL,
    [IPCountry]             NVARCHAR(100)    NULL,
    [Browser]               NVARCHAR(200)    NULL,
    [ScreenName]            NVARCHAR(200)    NULL,
    CONSTRAINT [PK_DepartmentMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO
